# version 3 so we got 3 stacks
version: '3'

# define some services
services:
  # 1. mongo
  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db # link the folders
    expose:
      - "27017" # hit us up, 27017
  # 2. kv
  # kv:
  #   image: redis:alpine
  #   volumes: 
  #     - redis-data:/data
  #   expose: 
  #     - "6379"
  # 3. app
  app:
    image: samnnodim/message-app # use image from dockerfile
    ports:
      - "80" # b/c 80 is exposed in the image
    links:
      - mongo
    depends_on: 
      - mongo
    environment: 
      - MONGO_URL=mongodb://mongo/messageApp
      # - REDIS_URL=redis

# define some volumes
volumes:
  mongo-data:
  # redis-data: